### ISSUE TITLE
Display a PCI Recommendation, with content, on the page in addition to everything else

### ISSUE THREAD

**Issue by giorgiosironi** [hivereview/thehive#242]
Scope is http://staging.hive.review/articles/10.1101/2020.06.03.20119925 only:

## Content

- [x] display endorsement text
- [x] display citations
- [x] display endorsement title
- [x] display author of recommendation
- [x] display endorsement date on article page

## ToDo

- [ ] do a styling run

## Refactoring

- [x] `fetch-pci-recommendation` should ~get a `-content` suffix~ match its implemented port with its name
- [ ] extract `axios.get` in `fetch-pci-recommendation` into a port
- [ ] unit tests for scraping
- [x] `GetRecommendations` should become `GetEndorsements` and similarly throughout the article page
- [ ] introduce `Maybe`/`Result` in fetching, where necessary
- [ ] `debug` log `Fetched PCI page` could be reduced/improved
- [ ] should citations really come from Crossref? Sizable investment and may be inconsistent with the text.

**Comment by giorgiosironi** [comment]
What we should include in the example ~recommendation~ endorsement content.

Title and author(s):
```
SARS-Cov-2 genome sequence analysis suggests rapid spread followed by epidemic slowdown in France
B. Jesse Shapiro based on reviews by Luca Ferretti and 2 anonymous reviewers
```

Text:
```
Sequencing and analyzing SARS-Cov-2 genomes in nearly real time has the potential to quickly confirm (and inform) our knowledge of, and response to, the current pandemic [1,2]. In this manuscript [3], Danesh and colleagues use the earliest set of available SARS-Cov-2 genome sequences available from France to make inferences about the timing of the major epidemic wave, the duration of infections, and the efficacy of lockdown measures. Their phylodynamic estimates -- based on fitting genomic data to molecular clock and transmission models -- are reassuringly close to estimates based on 'traditional' epidemiological methods: the French epidemic likely began in mid-January or early February 2020, and spread relatively rapidly (doubling every 3-5 days), with people remaining infectious for a median of 5 days [4,5]. These transmission parameters are broadly in line with estimates from China [6,7], but are currently unknown in France (in the absence of contact tracing data). By estimating the temporal reproductive number (Rt), the authors detected a slowing down of the epidemic in the most recent period of the study, after mid-March, supporting the efficacy of lockdown measures.
Along with the three other reviewers of this manuscript, I was impressed with the careful and exhaustive phylodynamic analyses reported by Danesh et al. [3]. Notably, they take care to show that the major results are robust to the choice of priors and to sampling. The authors are also careful to note that the results are based on a limited sample size of SARS-Cov-2 genomes, which may not be representative of all regions in France. Their analysis also focused on the dominant SARS-Cov-2 lineage circulating in France, which is also circulating in other countries. The variations they inferred in epidemic growth in France could therefore be reflective on broader control policies in Europe, not only those in France. Clearly more work is needed to fully unravel which control policies (and where) were most effective in slowing the spread of SARS-Cov-2, but Danesh et al. [3] set a solid foundation to build upon with more data. Overall this is an exemplary study, enabled by rapid and open sharing of sequencing data, which provides a template to be replicated and expanded in other countries and regions as they deal with their own localized instances of this pandemic. 
```

References:
```
[1] Grubaugh, N. D., Ladner, J. T., Lemey, P., Pybus, O. G., Rambaut, A., Holmes, E. C., & Andersen, K. G. (2019). Tracking virus outbreaks in the twenty-first century. Nature microbiology, 4(1), 10-19. doi: 10.1038/s41564-018-0296-2
[2] Fauver et al. (2020) Coast-to-Coast Spread of SARS-CoV-2 during the Early Epidemic in the United States. Cell, 181(5), 990-996.e5. doi: 10.1016/j.cell.2020.04.021
[3] Danesh, G., Elie, B., Michalakis, Y., Sofonea, M. T., Bal, A., Behillil, S., Destras, G., Boutolleau, D., Burrel, S., Marcelin, A.-G., Plantier, J.-C., Thibault, V., Simon-Loriere, E., van der Werf, S., Lina, B., Josset, L., Enouf, V. and Alizon, S. and the COVID SMIT PSL group (2020) Early phylodynamics analysis of the COVID-19 epidemic in France. medRxiv, 2020.06.03.20119925, ver. 3 peer-reviewed and recommended by PCI Evolutionary Biology. doi: 10.1101/2020.06.03.20119925
[4] Salje et al. (2020) Estimating the burden of SARS-CoV-2 in France. hal-pasteur.archives-ouvertes.fr/pasteur-02548181
[5] Sofonea, M. T., Reyné, B., Elie, B., Djidjou-Demasse, R., Selinger, C., Michalakis, Y. and Samuel Alizon, S. (2020) Epidemiological monitoring and control perspectives: application of a parsimonious modelling framework to the COVID-19 dynamics in France. medRxiv, 2020.05.22.20110593. doi: 10.1101/2020.05.22.20110593
[6] Rambaut, A. (2020) Phylogenetic analysis of nCoV-2019 genomes. virological.org/t/phylodynamic-analysis-176-genomes-6-mar-2020/356
[7] Li et al. (2020) Early transmission dynamics in Wuhan, China, of novel coronavirus–infected pneumonia. N Engl J Med, 382: 1199-1207. doi: 10.1056/NEJMoa2001316 
```

About these 3:

- title and author(s) (available also via Crossref). Take this from Crossref, only the author of the recommendation.
- text (not available via Crossref). Scrape it.
- references (available also via Crossref, they are only DOIs). Take this from Crossref, recursively resolving the DOIs.
