### ISSUE TITLE
Make title and meta-data full width of article page for all articles

### ISSUE THREAD

**Issue by erkannt** [hivereview/thehive#256]
- [x] remove badges
- [x] ~apply grid to inner content of article~ take out `<header>` from main content
- [x] remove semantic UI from meta data and title
- [x] add the classes from flavour B instead
- [x] line height of meta data
- [x] increase separation of navbar to title (navbar deserves restyle / semantic-ui removal)
