### ISSUE TITLE
Add https

### ISSUE THREAD

**Issue by kevinrutherford** [hivereview/thehive#7]
## Blockers

- [x] can't use CRDs required by cert-manager on k8s v1.14
- [x] cluster needs to be upgraded to at least 1.17
- [x] can't upgrade cluster without having first got a persistent DB

## ToDo

- [x] add ingress object to chart
- [x] create service for ingress to reach
- [x] what about DNS?
- [x] add an Ingress controller
- [x] attaching the Ingress controller to an AWS ELB
- [x] remove LoadBalancer Service
  - [x] make release
  - [x] rename ClusterIP service
- [x] make DNS entry configurable
- [x] setup ssl
  - [x] install cert-manager from jetstack chart
  - [x] configure ClusterIssuer for letsencrypt
    - [x] add tf-k8s-alpha provider to allow speccing custom k8s resources i.e. ClusterIssuer
  - [x] add tls section and request letsencrypt cert via annotation
- [x] handle www.hive.review in ingress instead of s3 bucket
  - [x] remove s3 bucket
  - [x] remove manual DNS entry for www.hive.review
  - [x] try [this](https://github.com/kubernetes/ingress-nginx/issues/2043#issuecomment-676479988) ingress setup?
- [x] consider [`asg_min_size = 3`](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/9ace344c57709ac5cd32da2d94ed6b6f7e9c1d28/docs/faq.md#why-does-changing-the-worker-groups-desired-count-not-do-anything)
- [x] limit cookies to https?
  - [x] koa session
  - [x] cookie consent
  - [x] middleware: only consider connection secure by using `APP_ORIGIN`
- [x] external services redirect here such as Twitter?
  - [x] change APP_ORIGIN to https
  - [x] change Twitter app settings on developer.twitter.com
  - [x] change checks on `APP_ORIGIN` to check `https://` prefix rather than presence/absence
- [x] understand which layer is doing the http-to-https redirect
- [x] update `NOTES.txt`

## Deprecations

- [x] Kubernetes 1.14 has deprecated Ingress `apiVersion` `extensions/v1beta1`
- [x] not using current version of ingress-nginx as we installed a version to be compatible with k8s 1.14
- [x] `external-dns` Helm chart comes from `stable` channel which is deprecated
- [x] `helm_repository` deprecated in tf provider
- [x] `cert-manager` CRDs use 1.14 compatible api, should now use non-deprecated api
  - the [helm-chart](https://github.com/jetstack/cert-manager/blob/ceccf6a04781162e879bdaf927ae33648ebc440e/deploy/manifests/BUILD.bazel#L21) automatically installs the old api CRD if installed on old k8s
  - updating CRD might be achieved by manually deleting the CRDs from the cluster and then making a deploy via github actions or by removing and readding the `cert-manager` chart via the `libero/infrastructure` repo

`pluto` deprecation report as of now:

```
pluto detect-helm --helm-version 3 -owide
NAME                                               NAMESPACE   KIND                           VERSION                                REPLACEMENT                       DEPRECATED   DEPRECATED IN   REMOVED   REMOVED IN
cert-manager/certificaterequests.cert-manager.io   default     CustomResourceDefinition       apiextensions.k8s.io/v1beta1           apiextensions.k8s.io/v1           true         v1.16.0         false     v1.19.0
cert-manager/certificates.cert-manager.io          default     CustomResourceDefinition       apiextensions.k8s.io/v1beta1           apiextensions.k8s.io/v1           true         v1.16.0         false     v1.19.0
cert-manager/challenges.acme.cert-manager.io       default     CustomResourceDefinition       apiextensions.k8s.io/v1beta1           apiextensions.k8s.io/v1           true         v1.16.0         false     v1.19.0
cert-manager/clusterissuers.cert-manager.io        default     CustomResourceDefinition       apiextensions.k8s.io/v1beta1           apiextensions.k8s.io/v1           true         v1.16.0         false     v1.19.0
cert-manager/issuers.cert-manager.io               default     CustomResourceDefinition       apiextensions.k8s.io/v1beta1           apiextensions.k8s.io/v1           true         v1.16.0         false     v1.19.0
cert-manager/orders.acme.cert-manager.io           default     CustomResourceDefinition       apiextensions.k8s.io/v1beta1           apiextensions.k8s.io/v1           true         v1.16.0         false     v1.19.0
cert-manager/cert-manager-webhook                  default     MutatingWebhookConfiguration   admissionregistration.k8s.io/v1beta1   admissionregistration.k8s.io/v1   true         v1.16.0         false     v1.19.0
prc--prod/prc--prod--frontend                      default     Ingress                        extensions/v1beta1                     networking.k8s.io/v1beta1         true         v1.14.0         false     v1.22.0
prc--staging/prc--staging--frontend                default     Ingress                        extensions/v1beta1                     networking.k8s.io/v1beta1         true         v1.14.0         false     v1.22.0

```

**Comment by erkannt** [comment]
Looks like applying k8s-manifests with terraform requires the [alpha version of their k8s provider](https://github.com/hashicorp/terraform-provider-kubernetes-alpha).

Long term I don't like the thought of having to wrap k8s yaml manifests in HCL. I feel managing the k8s manifests in a separate repo and using e.g. flux, argoCD or gitops-toolkit is nicer to maintain.

**Comment by giorgiosironi** [comment]
WWW redirect on http:

```
[13:55:37][giorgio@Newton:~/code/prc]$ curl -v http://www.hive.review/ping
...
* Connected to www.hive.review (3.92.118.185) port 80 (#0)
> GET /ping HTTP/1.1
> Host: www.hive.review
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 308 Permanent Redirect
< Server: nginx/1.19.2
< Date: Wed, 21 Oct 2020 12:55:43 GMT
< Content-Type: text/html
< Content-Length: 171
< Connection: keep-alive
< Location: http://hive.review/ping
< 
<html>
<head><title>308 Permanent Redirect</title></head>
...
```

WWW redirect on https:
```
[13:57:30][giorgio@Newton:~/code/prc]$ curl -v https://www.hive.review/ping
*   Trying 18.206.128.132...
* TCP_NODELAY set
* Connected to www.hive.review (18.206.128.132) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
...
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=hive.review
*  start date: Oct 21 11:43:36 2020 GMT
*  expire date: Jan 19 11:43:36 2021 GMT
*  subjectAltName: host "www.hive.review" matched cert's "www.hive.review"
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
...
> GET /ping HTTP/2
> Host: www.hive.review
> User-Agent: curl/7.58.0
> Accept: */*
> 
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
< HTTP/2 308 
< server: nginx/1.19.2
< date: Wed, 21 Oct 2020 12:57:33 GMT
< content-type: text/html
< content-length: 171
< location: https://hive.review/ping
< 
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
<html>
<head><title>308 Permanent Redirect</title></head>
...
```

**Comment by giorgiosironi** [comment]
https://developer.twitter.com/en/portal/projects/1297805502685093888/apps/18623712/settings mentions `http://` URLs. Tried to change them to HTTPS, and `/log-in` broke with `Internal Server Error` so rolling back.
![Screenshot_2020-10-21 Twitter Developers](https://user-images.githubusercontent.com/160299/96729838-7d74ab00-13ad-11eb-85a8-9ba672401a5f.png)
The terms and conditions seem to be fine:
![Screenshot_2020-10-21 Twitter Developers(1)](https://user-images.githubusercontent.com/160299/96729843-7e0d4180-13ad-11eb-8429-6bc9ba25f071.png)

**Comment by giorgiosironi** [comment]
Route of investigation in case of problems when installing CRDs: https://github.com/hashicorp/terraform-provider-kubernetes-alpha/issues/72#issuecomment-654202679
